import { AlertTriangle } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useIsDarkMode } from "@/hooks/useIsDarkMode";

/** Diagram labels that are file paths can deep-link into the Dependencies tab. */
const PATH_LIKE = /^[\w.-]+(?:\/[\w.-]+)+\.\w+$/;

/**
 * Renders a deterministic Mermaid diagram (generated by the analysis
 * pipeline) as an inline SVG. Theme-aware and failure-safe: a diagram that
 * doesn't parse falls back to its source, never a crash. With a projectId,
 * path-labeled nodes (sequence participants, file boxes) become clickable
 * deep-links into the Dependencies tab (audit §7) — labels that aren't
 * files stay inert rather than linking somewhere wrong.
 */
export function MermaidDiagram({ code, label, projectId }: { code: string; label?: string; projectId?: string }) {
  const isDark = useIsDarkMode();
  const navigate = useNavigate();
  const containerRef = useRef<HTMLDivElement>(null);
  const [failed, setFailed] = useState(false);
  const reactId = useId();

  useEffect(() => {
    let cancelled = false;
    setFailed(false);
    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: isDark ? "dark" : "neutral",
          themeVariables: {
            fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
            fontSize: "13px",
          },
        });
        const id = `mmd-${reactId.replace(/[^a-zA-Z0-9]/g, "")}-${isDark ? "d" : "l"}`;
        const { svg } = await mermaid.render(id, code);
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
          const el = containerRef.current.querySelector("svg");
          if (el) {
            el.style.maxWidth = "100%";
            el.style.height = "auto";
          }
          if (el && projectId) {
            for (const textEl of el.querySelectorAll("text")) {
              const t = textEl.textContent?.trim() ?? "";
              if (!PATH_LIKE.test(t)) continue;
              (textEl as SVGTextElement).style.cursor = "pointer";
              (textEl as SVGTextElement).style.textDecoration = "underline dotted";
              textEl.addEventListener("click", () =>
                navigate(`/projects/${projectId}/dependencies?focus=${encodeURIComponent(t)}`),
              );
            }
          }
        }
      } catch {
        if (!cancelled) setFailed(true);
      }
    })();
    return () => { cancelled = true; };
  }, [code, isDark, reactId, projectId, navigate]);

  if (failed) {
    return (
      <figure className="overflow-x-auto rounded-lg border border-border bg-card p-3">
        {label && <figcaption className="section-label mb-2">{label}</figcaption>}
        <p className="mb-2 flex items-center gap-1.5 text-[0.6875rem] text-muted-foreground">
          <AlertTriangle className="h-3 w-3 shrink-0" />
          Couldn't render this diagram; showing its source instead.
        </p>
        <pre className="overflow-x-auto rounded-md border border-border bg-muted px-3 py-2 text-[0.6875rem] text-muted-foreground">
          {code}
        </pre>
      </figure>
    );
  }

  return (
    <figure className="overflow-x-auto rounded-lg border border-border bg-card p-3">
      {label && <figcaption className="section-label mb-2">{label}</figcaption>}
      <div ref={containerRef} role="img" aria-label={label ?? "Diagram"} />
    </figure>
  );
}
