import { AlertTriangle } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useIsDarkMode } from "@/hooks/useIsDarkMode";

/** Diagram labels that are file paths can deep-link into the Dependencies tab. */
const PATH_LIKE = /^[\w.-]+(?:\/[\w.-]+)+\.\w+$/;

/**
 * Records how big this figure would be if nothing constrained it, on the
 * figure itself, the moment mermaid's SVG lands.
 *
 * The Enlarge modal needs that number BEFORE it opens, so it can size its
 * frame in one synchronous step instead of measuring a diagram that does not
 * exist yet and correcting itself afterwards. The inline preview has already
 * rendered by the time anyone can click Enlarge, so the answer is sitting
 * here; publishing it costs one forced layout per render and saves the modal
 * an entire observe-measure-resize-refit round trip.
 *
 * Sizes are the FIGURE's, not the SVG's, because the figure is what the modal
 * stage lays out: the caption, padding and border are part of the box it has
 * to frame. Both are read from the live element rather than assumed, so a
 * change to the figure's padding or the caption's font cannot silently make
 * every modal 26px too narrow.
 */
function publishNaturalSize(svg: SVGElement, naturalWidth: number) {
  const figure = svg.closest("figure");
  if (!figure || !(naturalWidth > 0)) return;
  // The viewBox is the only thing that survives being width-constrained, so
  // the aspect ratio comes from it rather than from the rendered height.
  const [, , boxWidth, boxHeight] = svg.getAttribute("viewBox")?.split(/[\s,]+/).map(Number) ?? [];
  const ratio = boxWidth && boxHeight && boxWidth > 0 ? boxHeight / boxWidth : null;
  const svgBox = svg.getBoundingClientRect();
  const naturalHeight = ratio ? naturalWidth * ratio : svgBox.height;
  if (!(naturalHeight > 0)) return;

  const style = getComputedStyle(figure);
  const chromeX =
    parseFloat(style.paddingLeft) +
    parseFloat(style.paddingRight) +
    parseFloat(style.borderLeftWidth) +
    parseFloat(style.borderRightWidth);
  // Vertically the figure is a plain block, so whatever it measures over the
  // SVG it contains IS the chrome: padding, border, caption and its margin.
  const chromeY = figure.getBoundingClientRect().height - svgBox.height;
  figure.dataset.naturalWidth = String(Math.round(naturalWidth + chromeX));
  figure.dataset.naturalHeight = String(Math.round(naturalHeight + Math.max(0, chromeY)));
}

/**
 * Renders a deterministic Mermaid diagram (generated by the analysis
 * pipeline) as an inline SVG. Theme-aware and failure-safe: a diagram that
 * doesn't parse falls back to its source, never a crash. With a projectId,
 * path-labeled nodes (sequence participants, file boxes) become clickable
 * deep-links into the Dependencies tab (audit §7) — labels that aren't
 * files stay inert rather than linking somewhere wrong.
 */
export function MermaidDiagram({ code, label, projectId }: { code: string; label?: string; projectId?: string }) {
  const isDark = useIsDarkMode();
  const navigate = useNavigate();
  const containerRef = useRef<HTMLDivElement>(null);
  const [failed, setFailed] = useState(false);
  const reactId = useId();

  useEffect(() => {
    let cancelled = false;
    setFailed(false);
    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: isDark ? "dark" : "neutral",
          themeVariables: {
            fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
            fontSize: "13px",
            // Dark theme only: mermaid derives the edge-label chip from
            // `lighten(labelBackground, 25)` = ~34% grey, and its label text is
            // #ccc — 4.4:1, the one contrast failure the M5 visual audit found
            // across every tab and both themes (it measured 4.43 on "depends
            // on" in the reader's topology diagram; the same pair computes to
            // 4.45). Reusing the node fill instead puts edge labels on the same
            // material as the boxes they connect and takes the pair to 10.2:1.
            // Left alone in light/neutral, which already passes.
            ...(isDark ? { edgeLabelBackground: "#1f2020" } : {}),
          },
        });
        const id = `mmd-${reactId.replace(/[^a-zA-Z0-9]/g, "")}-${isDark ? "d" : "l"}`;
        const { svg } = await mermaid.render(id, code);
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
          const el = containerRef.current.querySelector("svg");
          if (el) {
            // Mermaid emits `width="100%"` plus an inline
            // `max-width: <natural width>px`, i.e. "as wide as the container,
            // never wider than the size it was laid out at". That cap is what
            // stops a four-participant sequence diagram stretching across the
            // full card with its labels blown up to match, so it must survive.
            //
            // Stated the OTHER way round — `width: <natural>px` capped by
            // `max-width: 100%` — it renders at exactly the same size, because
            // both spell min(natural, container). The difference is what a
            // shrink-to-fit parent can see. An <svg> whose width is a
            // percentage has no intrinsic width, so CSS falls back to the
            // 300x150 default object size, and any container sized to its
            // content measures 300px whatever the diagram actually is
            // (measured in Chrome: a 320px, a 1100px and a 6979px diagram all
            // reported 326px). The Enlarge modal sizes itself from that
            // measurement, so without this it would open the same box for a
            // two-participant sequence diagram and a 37-table ER.
            const natural = Number.parseFloat(el.style.maxWidth);
            if (Number.isFinite(natural) && natural > 0) {
              el.style.width = `${natural}px`;
              el.style.maxWidth = "100%";
            }
            // The viewBox carries the aspect ratio, so a width-constrained svg
            // scales its height rather than cropping.
            el.style.height = "auto";
            // An <svg> is inline by default, so one narrower than its figure
            // (which is every diagram whose natural width is under the card's)
            // sat hard against the left edge with all the slack on the right.
            // `display: block` is what makes the auto margins resolve to equal
            // halves; it also drops the inline baseline gap under the diagram.
            // The Enlarge stage measures this same box, so centring here is
            // also what centres the diagram inside the modal.
            el.style.display = "block";
            el.style.marginInline = "auto";
            publishNaturalSize(el, natural);
          }
          if (el && projectId) {
            for (const textEl of el.querySelectorAll("text")) {
              const t = textEl.textContent?.trim() ?? "";
              if (!PATH_LIKE.test(t)) continue;
              (textEl as SVGTextElement).style.cursor = "pointer";
              (textEl as SVGTextElement).style.textDecoration = "underline dotted";
              textEl.addEventListener("click", () =>
                navigate(`/projects/${projectId}/dependencies?focus=${encodeURIComponent(t)}`),
              );
            }
          }
        }
      } catch {
        if (!cancelled) setFailed(true);
      }
    })();
    return () => { cancelled = true; };
  }, [code, isDark, reactId, projectId, navigate]);

  if (failed) {
    return (
      <figure className="overflow-x-auto rounded-lg border border-border bg-card p-3">
        {label && <figcaption className="section-label mb-2">{label}</figcaption>}
        <p className="mb-2 flex items-center gap-1.5 text-[0.6875rem] text-muted-foreground">
          <AlertTriangle className="h-3 w-3 shrink-0" />
          Couldn't render this diagram; showing its source instead.
        </p>
        <pre className="overflow-x-auto rounded-md border border-border bg-muted px-3 py-2 text-[0.6875rem] text-muted-foreground">
          {code}
        </pre>
      </figure>
    );
  }

  return (
    <figure className="overflow-x-auto rounded-lg border border-border bg-card p-3">
      {label && <figcaption className="section-label mb-2">{label}</figcaption>}
      <div ref={containerRef} role="img" aria-label={label ?? "Diagram"} />
    </figure>
  );
}
