export type WalkthroughConfidence = "high" | "medium" | "low";
export type StopStatus = "draft" | "reviewed";

export interface WalkthroughStop {
  id: string;
  label: string;
  filePath: string;
  lineStart: number;
  lineEnd: number;
  explanation: string;
  confidence: WalkthroughConfidence;
  status: StopStatus;
  codeLines: Array<{ lineNum: number; content: string }>;
}

export interface WalkthroughWorkflow {
  id: string;
  name: string;
  description: string;
  role: string;
  stops: WalkthroughStop[];
  status: "draft" | "reviewed";
  generatedAt: string;
}

export const MOCK_WORKFLOWS: WalkthroughWorkflow[] = [
  {
    id: "auth-flow",
    name: "Auth flow",
    description: "How a JWT token is validated on every protected API request",
    role: "backend",
    status: "draft",
    generatedAt: "2026-06-17T08:00:00Z",
    stops: [
      {
        id: "route-registered",
        label: "Route registered",
        filePath: "src/server.ts",
        lineStart: 34,
        lineEnd: 35,
        confidence: "high",
        status: "reviewed",
        explanation:
          "The payment routes are mounted on the app at startup (line 34). Every /payments request enters through this router before reaching any handler.",
        codeLines: [
          { lineNum: 28, content: "const app = express()" },
          { lineNum: 29, content: "app.set('trust proxy', 1)" },
          { lineNum: 30, content: "app.use(express.json())" },
          { lineNum: 31, content: "app.use(express.urlencoded({ extended: true }))" },
          { lineNum: 32, content: "" },
          { lineNum: 33, content: "// register feature routers" },
          { lineNum: 34, content: "app.use('/api/payments', paymentRouter)" },
          { lineNum: 35, content: "app.use('/api/auth',     authRouter)" },
          { lineNum: 36, content: "" },
          { lineNum: 37, content: "app.listen(PORT, () => console.log(`Server on :${PORT}`))" },
          { lineNum: 38, content: "export default app" },
        ],
      },
      {
        id: "auth-middleware",
        label: "Auth middleware",
        filePath: "src/middleware/auth.ts",
        lineStart: 10,
        lineEnd: 14,
        confidence: "high",
        status: "reviewed",
        explanation:
          "The authenticate middleware extracts the Bearer token from the Authorization header and validates it against Supabase. Requests without a valid token are rejected with 401 before any route handler runs.",
        codeLines: [
          { lineNum: 5,  content: "export async function authenticate(" },
          { lineNum: 6,  content: "  req: Request," },
          { lineNum: 7,  content: "  res: Response," },
          { lineNum: 8,  content: "  next: NextFunction," },
          { lineNum: 9,  content: ") {" },
          { lineNum: 10, content: "  const token = req.headers.authorization?.split(' ')[1]" },
          { lineNum: 11, content: "  if (!token) return res.status(401).json({ error: 'No token' })" },
          { lineNum: 12, content: "" },
          { lineNum: 13, content: "  const { data, error } = await supabase.auth.getUser(token)" },
          { lineNum: 14, content: "  if (error || !data.user) return res.status(401).json({ error: 'Invalid token' })" },
          { lineNum: 15, content: "" },
          { lineNum: 16, content: "  req.user = data.user" },
          { lineNum: 17, content: "  next()" },
          { lineNum: 18, content: "}" },
        ],
      },
      {
        id: "validate-body",
        label: "Validate body",
        filePath: "src/routes/payments.ts",
        lineStart: 25,
        lineEnd: 27,
        confidence: "high",
        status: "draft",
        explanation:
          "The request body is validated with a Zod schema before any processing occurs. If validation fails, a 422 with field-level errors is returned immediately — no service-layer code runs.",
        codeLines: [
          { lineNum: 18, content: "const createChargeSchema = z.object({" },
          { lineNum: 19, content: "  amount:   z.number().positive().int()," },
          { lineNum: 20, content: "  currency: z.string().length(3)," },
          { lineNum: 21, content: "  source:   z.string().startsWith('tok_')," },
          { lineNum: 22, content: "})" },
          { lineNum: 23, content: "" },
          { lineNum: 24, content: "router.post('/charges', authenticate, async (req, res) => {" },
          { lineNum: 25, content: "  const parsed = createChargeSchema.safeParse(req.body)" },
          { lineNum: 26, content: "  if (!parsed.success)" },
          { lineNum: 27, content: "    return res.status(422).json({ errors: parsed.error.flatten() })" },
          { lineNum: 28, content: "" },
          { lineNum: 29, content: "  const charge = await chargeService.create(parsed.data, req.user.id)" },
          { lineNum: 30, content: "  res.status(201).json(charge)" },
          { lineNum: 31, content: "})" },
        ],
      },
      {
        id: "service-call",
        label: "Service call",
        filePath: "src/services/chargeService.ts",
        lineStart: 21,
        lineEnd: 25,
        confidence: "high",
        status: "draft",
        explanation:
          "chargeService.create() contains the core business logic. It checks idempotency first, calls the Stripe API, then persists the payment record. The service layer is the only place that talks to external APIs.",
        codeLines: [
          { lineNum: 12, content: "export async function create(" },
          { lineNum: 13, content: "  data: CreateChargeInput," },
          { lineNum: 14, content: "  userId: string," },
          { lineNum: 15, content: "): Promise<Payment> {" },
          { lineNum: 16, content: "  const existing = await db('payments')" },
          { lineNum: 17, content: "    .where('idempotency_key', data.idempotencyKey).first()" },
          { lineNum: 18, content: "  if (existing) return existing" },
          { lineNum: 19, content: "" },
          { lineNum: 20, content: "  // charge via Stripe" },
          { lineNum: 21, content: "  const stripeCharge = await stripe.charges.create({" },
          { lineNum: 22, content: "    amount:   data.amount," },
          { lineNum: 23, content: "    currency: data.currency," },
          { lineNum: 24, content: "    source:   data.source," },
          { lineNum: 25, content: "  })" },
          { lineNum: 26, content: "" },
          { lineNum: 27, content: "  return Payment.create({" },
          { lineNum: 28, content: "    userId," },
          { lineNum: 29, content: "    amount:         data.amount," },
          { lineNum: 30, content: "    stripeChargeId:  stripeCharge.id," },
          { lineNum: 31, content: "    idempotencyKey:  data.idempotencyKey," },
          { lineNum: 32, content: "  })" },
          { lineNum: 33, content: "}" },
        ],
      },
      {
        id: "db-write",
        label: "DB write",
        filePath: "src/models/Payment.ts",
        lineStart: 31,
        lineEnd: 40,
        confidence: "high",
        status: "draft",
        explanation:
          "Payment.create() inserts the record with status 'pending'. The idempotency_key column has a unique constraint as a DB-level safety net against duplicate charges.",
        codeLines: [
          { lineNum: 29, content: "static async create(attrs: Partial<Payment>): Promise<Payment> {" },
          { lineNum: 30, content: "  const [row] = await db('payments')" },
          { lineNum: 31, content: "    .insert({" },
          { lineNum: 32, content: "      user_id:          attrs.userId," },
          { lineNum: 33, content: "      amount:           attrs.amount," },
          { lineNum: 34, content: "      currency:         attrs.currency," },
          { lineNum: 35, content: "      status:           'pending'," },
          { lineNum: 36, content: "      stripe_charge_id: attrs.stripeChargeId," },
          { lineNum: 37, content: "      idempotency_key:  attrs.idempotencyKey," },
          { lineNum: 38, content: "    })" },
          { lineNum: 39, content: "    .returning('*')" },
          { lineNum: 40, content: "  emitter.emit('payment.created', row)" },
          { lineNum: 41, content: "  return row" },
          { lineNum: 42, content: "}" },
        ],
      },
      {
        id: "emit-event",
        label: "Emit event",
        filePath: "src/events/emitter.ts",
        lineStart: 14,
        lineEnd: 19,
        confidence: "medium",
        status: "draft",
        explanation:
          "After the DB write succeeds, a 'payment.created' event is emitted. Listeners handle webhook delivery and audit logging asynchronously — they do not block the HTTP response.",
        codeLines: [
          { lineNum: 10, content: "import EventEmitter from 'events'" },
          { lineNum: 11, content: "" },
          { lineNum: 12, content: "export const emitter = new EventEmitter()" },
          { lineNum: 13, content: "" },
          { lineNum: 14, content: "emitter.on('payment.created', async (payment: Payment) => {" },
          { lineNum: 15, content: "  await webhookService.deliver('payment.created', payment)" },
          { lineNum: 16, content: "  await auditLog.record({" },
          { lineNum: 17, content: "    event:    'payment.created'," },
          { lineNum: 18, content: "    entityId: payment.id," },
          { lineNum: 19, content: "  })" },
          { lineNum: 20, content: "})" },
        ],
      },
      {
        id: "response",
        label: "Response",
        filePath: "src/routes/payments.ts",
        lineStart: 30,
        lineEnd: 30,
        confidence: "high",
        status: "draft",
        explanation:
          "The newly created charge is returned with a 201 Created status. The response body is the full Payment record including the generated ID and Stripe charge ID.",
        codeLines: [
          { lineNum: 24, content: "router.post('/charges', authenticate, async (req, res) => {" },
          { lineNum: 25, content: "  const parsed = createChargeSchema.safeParse(req.body)" },
          { lineNum: 26, content: "  if (!parsed.success)" },
          { lineNum: 27, content: "    return res.status(422).json({ errors: parsed.error.flatten() })" },
          { lineNum: 28, content: "" },
          { lineNum: 29, content: "  const charge = await chargeService.create(parsed.data, req.user.id)" },
          { lineNum: 30, content: "  res.status(201).json(charge)" },
          { lineNum: 31, content: "})" },
        ],
      },
      {
        id: "audit-log",
        label: "Audit log",
        filePath: "src/lib/auditLog.ts",
        lineStart: 4,
        lineEnd: 11,
        confidence: "medium",
        status: "draft",
        explanation:
          "Every payment event is written to the audit_logs table for compliance and debugging. This runs asynchronously after the HTTP response is sent, so it adds no latency to the caller.",
        codeLines: [
          { lineNum: 1,  content: "import { db } from './db'" },
          { lineNum: 2,  content: "" },
          { lineNum: 3,  content: "export const auditLog = {" },
          { lineNum: 4,  content: "  async record(entry: { event: string; entityId: string; meta?: object }) {" },
          { lineNum: 5,  content: "    await db('audit_logs').insert({" },
          { lineNum: 6,  content: "      event:      entry.event," },
          { lineNum: 7,  content: "      entity_id:  entry.entityId," },
          { lineNum: 8,  content: "      meta:       JSON.stringify(entry.meta ?? {})," },
          { lineNum: 9,  content: "      created_at: new Date().toISOString()," },
          { lineNum: 10, content: "    })" },
          { lineNum: 11, content: "  }," },
          { lineNum: 12, content: "}" },
        ],
      },
    ],
  },
  {
    id: "charge-creation",
    name: "Charge creation",
    description: "Full lifecycle of a new payment charge from API request to DB record",
    role: "backend",
    status: "draft",
    generatedAt: "2026-06-17T08:00:00Z",
    stops: [
      {
        id: "post-charges",
        label: "POST /charges",
        filePath: "src/routes/payments.ts",
        lineStart: 24,
        lineEnd: 24,
        confidence: "high",
        status: "reviewed",
        explanation:
          "Charge creation begins at the POST /charges endpoint. The authenticate middleware is applied as the second argument, so the token is validated before the handler body runs.",
        codeLines: [
          { lineNum: 18, content: "const createChargeSchema = z.object({" },
          { lineNum: 19, content: "  amount:   z.number().positive().int()," },
          { lineNum: 20, content: "  currency: z.string().length(3)," },
          { lineNum: 21, content: "  source:   z.string().startsWith('tok_')," },
          { lineNum: 22, content: "})" },
          { lineNum: 23, content: "" },
          { lineNum: 24, content: "router.post('/charges', authenticate, async (req, res) => {" },
          { lineNum: 25, content: "  const parsed = createChargeSchema.safeParse(req.body)" },
          { lineNum: 26, content: "  if (!parsed.success)" },
          { lineNum: 27, content: "    return res.status(422).json({ errors: parsed.error.flatten() })" },
          { lineNum: 28, content: "})" },
        ],
      },
      {
        id: "idempotency-check",
        label: "Idempotency check",
        filePath: "src/services/chargeService.ts",
        lineStart: 16,
        lineEnd: 18,
        confidence: "high",
        status: "draft",
        explanation:
          "Before hitting Stripe, the service checks if a payment with this idempotency key already exists in the DB. This prevents duplicate charges if the client retries due to a network error.",
        codeLines: [
          { lineNum: 12, content: "export async function create(data: CreateChargeInput, userId: string) {" },
          { lineNum: 13, content: "" },
          { lineNum: 14, content: "  // check idempotency before touching Stripe" },
          { lineNum: 15, content: "  const existing = await db('payments')" },
          { lineNum: 16, content: "    .where('idempotency_key', data.idempotencyKey)" },
          { lineNum: 17, content: "    .first()" },
          { lineNum: 18, content: "  if (existing) return existing" },
          { lineNum: 19, content: "" },
          { lineNum: 20, content: "  const stripeCharge = await stripe.charges.create({..." },
        ],
      },
      {
        id: "stripe-call",
        label: "Stripe API call",
        filePath: "src/lib/stripe.ts",
        lineStart: 5,
        lineEnd: 8,
        confidence: "medium",
        status: "draft",
        explanation:
          "The Stripe client is a singleton instantiated with the secret key from config. All Stripe calls go through this object. Changes to this file require a security review from @payments-platform.",
        codeLines: [
          { lineNum: 1, content: "import Stripe from 'stripe'" },
          { lineNum: 2, content: "import { config } from './config'" },
          { lineNum: 3, content: "" },
          { lineNum: 4, content: "// DO NOT modify without security review (@payments-platform)" },
          { lineNum: 5, content: "export const stripe = new Stripe(config.STRIPE_SECRET_KEY, {" },
          { lineNum: 6, content: "  apiVersion: '2023-10-16'," },
          { lineNum: 7, content: "  timeout:     10_000," },
          { lineNum: 8, content: "})" },
        ],
      },
      {
        id: "persist-record",
        label: "Persist record",
        filePath: "src/models/Payment.ts",
        lineStart: 31,
        lineEnd: 38,
        confidence: "high",
        status: "draft",
        explanation:
          "The successful Stripe charge is persisted to the payments table with status 'pending'. It transitions to 'completed' when Stripe's webhook confirms the charge asynchronously.",
        codeLines: [
          { lineNum: 27, content: "  return Payment.create({" },
          { lineNum: 28, content: "    userId," },
          { lineNum: 29, content: "    amount:         data.amount," },
          { lineNum: 30, content: "    currency:        data.currency," },
          { lineNum: 31, content: "    stripeChargeId:  stripeCharge.id," },
          { lineNum: 32, content: "    idempotencyKey:  data.idempotencyKey," },
          { lineNum: 33, content: "    status:          'pending'," },
          { lineNum: 34, content: "  })" },
          { lineNum: 35, content: "}" },
        ],
      },
    ],
  },
];
